# Generated by Django 3.0 on 2022-09-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('is_chief', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.Department')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['surname'], name='staff_emplo_surname_162d07_idx'),
        ),
    ]
