# Generated by Django 3.0 on 2022-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_chief',
            field=models.BooleanField(default=False),
        ),
    ]
